"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
const API="/api";
const display=x=>x?.displayName||"Bazara user";
export default function InboxPanel({token,role}){
 const[list,setList]=useState([]),[active,setActive]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(""),[retry,setRetry]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const myId=useMemo(()=>{try{return Number(JSON.parse(atob(token.split(".")[1])).id);}catch{return 0;}},[token]);
 const request=useCallback(async(path,options={})=>{const r=await fetch(API+path,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok)throw Error(d.message||"Inbox request failed");return d;},[token]);
 const refresh=useCallback(async()=>{try{setList((await request("/inbox/conversations?limit=25")).items||[]);}catch(e){setError(e.message);}},[request]);
 useEffect(()=>{refresh();},[refresh]);
 async function open(c){setActive(c);setError("");try{const d=await request(`/inbox/conversations/${c.conversationId}/messages?limit=50`);setMessages(d.items||[]);const last=d.items?.at(-1);if(last)await request(`/inbox/conversations/${c.conversationId}/read`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lastReadMessageId:last.id})});setList(xs=>xs.map(x=>x.conversationId===c.conversationId?{...x,hasUnread:false}:x));}catch(e){setError(e.message);}}
 async function send(){const body=text.trim();if(!body||busy)return;const clientMessageId=retry||crypto.randomUUID();setRetry(clientMessageId);setBusy(true);try{const m=await request(`/inbox/conversations/${active.conversationId}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body,clientMessageId})});setMessages(xs=>xs.some(x=>x.id===m.id)?xs:[...xs,m]);setText("");setRetry("");setError("");refresh();}catch(e){setError(e.message+" — Retry");}finally{setBusy(false);}}
 return <section><p className="marketplace-eyebrow">Messages</p><h2 className="mt-2 text-3xl font-bold">Inbox</h2><div className="mt-7 min-h-[32rem] overflow-hidden rounded-2xl border border-white/10 bg-[#0d0d0d] text-white md:grid md:grid-cols-[20rem_1fr]">
 <aside className={`border-white/10 md:border-r ${active?"hidden md:block":""}`}><h3 className="border-b border-white/10 p-4 font-bold">Conversations</h3>{list.length?list.map(c=><button key={c.conversationId} onClick={()=>open(c)} className="block w-full border-b border-white/5 p-4 text-left hover:bg-white/5"><span className={c.hasUnread?"font-extrabold":"font-semibold text-zinc-300"}>{display(c.counterpart)}</span>{c.hasUnread&&<span className="ml-2 inline-block h-2 w-2 rounded-full bg-red-500" aria-label="Unread"/>}<p className="mt-1 truncate text-xs text-zinc-400">{c.product?.name||"Product enquiry"} · Qty {c.quantity}</p><p className="mt-2 truncate text-sm text-zinc-400">{c.lastMessage?.body||"Product enquiry created"}</p></button>):<p className="p-8 text-sm leading-6 text-zinc-400">{role==="VENDOR"?"No conversations yet. When buyers enquire about your products, their messages will appear here.":"No conversations yet. Send a product enquiry to start talking with a supplier."}</p>}</aside>
 <main className={active?"flex min-h-[32rem] flex-col":"hidden items-center justify-center text-zinc-500 md:flex"}>{active&&<><header className="border-b border-white/10 p-4"><button onClick={()=>setActive(null)} className="mb-2 text-sm font-bold text-red-400 md:hidden">← Back</button><strong>{display(active.counterpart)}</strong><p className="text-xs text-zinc-400">{active.product?.name} · Quantity {active.quantity}{active.product&&<Link href={`/product/${active.product.id}`} className="ml-2 text-red-400">View Product</Link>}</p></header><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map(m=>m.type==="INQUIRY_CREATED"?<p key={m.id} className="mx-auto w-fit rounded-full bg-white/5 px-3 py-2 text-xs text-zinc-400">Product enquiry created</p>:<div key={m.id} className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm ${m.senderId===myId?"ml-auto bg-red-600":"bg-[#222]"}`}><p className="whitespace-pre-wrap">{m.body}</p></div>)}</div><footer className="border-t border-white/10 p-3"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}}} rows={2} maxLength={4000} placeholder="Type a message..." className="w-full resize-none rounded-xl border border-white/10 bg-[#191919] p-3 text-sm outline-none focus:border-red-500"/>{error&&<p role="alert" className="mt-2 text-xs text-red-400">{error}</p>}<button onClick={send} disabled={busy||!text.trim()} className="mt-2 rounded-xl bg-red-600 px-5 py-2 text-sm font-bold disabled:opacity-50">{busy?"Sending...":retry?"Retry":"Send"}</button></footer></>}{!active&&<p>Select a conversation</p>}</main>
 </div></section>;
}
