"use client";
import { useMemo, useState } from "react";
import { displayName, EmptyState, formatDate, SectionTitle, StatusBadge } from "./AdminUi";
export default function AdminUsers({ users }) {
  const [query,setQuery]=useState(""); const [role,setRole]=useState("ALL"); const [verification,setVerification]=useState("ALL"); const [sort,setSort]=useState("NEWEST");
  const visible=useMemo(()=>users.filter((user)=>{const text=[displayName(user),user.email,user.companyName].join(" ").toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(role==="ALL"||user.role===role)&&(verification==="ALL"||(verification==="VERIFIED")===Boolean(user.isVerified));}).sort((a,b)=>sort==="OLDEST"?new Date(a.createdAt)-new Date(b.createdAt):sort==="NAME"?displayName(a).localeCompare(displayName(b)):new Date(b.createdAt)-new Date(a.createdAt)),[query,role,sort,users,verification]);
  return <section><SectionTitle eyebrow="Identity and access" title="Users" description="Safe account fields only; credentials and private authentication data are never displayed."/><div className="mt-6 grid gap-3 md:grid-cols-4"><label className="text-sm font-bold text-slate-700">Search<input value={query} onChange={(e)=>setQuery(e.target.value)} type="search" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal" placeholder="Name, email, company"/></label><Filter label="Role" value={role} onChange={setRole} options={["ALL","ADMIN","VENDOR","CLIENT"]}/><Filter label="Verification" value={verification} onChange={setVerification} options={["ALL","VERIFIED","UNVERIFIED"]}/><Filter label="Sort" value={sort} onChange={setSort} options={["NEWEST","OLDEST","NAME"]}/></div>{!visible.length?<div className="mt-6"><EmptyState title="No users found" description="No accounts match the current filters."/></div>:<div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-[850px] w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{["Name","Email","Role","Company","Verification","Created"].map((label)=><th key={label} scope="col" className="px-4 py-3 font-bold">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-200">{visible.map((user)=><tr key={user.id}><td className="px-4 py-4 font-bold">{displayName(user)}</td><td className="max-w-64 break-all px-4 py-4">{user.email}</td><td className="px-4 py-4"><StatusBadge value={user.role}/></td><td className="px-4 py-4">{user.companyName||"—"}</td><td className="px-4 py-4"><StatusBadge value={user.isVerified?"Verified":"Unverified"}/></td><td className="px-4 py-4 whitespace-nowrap">{formatDate(user.createdAt)}</td></tr>)}</tbody></table></div>}</section>;
}
function Filter({label,value,onChange,options}){return <label className="text-sm font-bold text-slate-700">{label}<select value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal">{options.map((option)=><option key={option}>{option}</option>)}</select></label>}
