"use client";

import { formatDate, formatMoney, StatusBadge, supplierName } from "./RfqUi";

export default function BuyerRfqList({ rfqs, decisionId, onDecision }) {
  return <div className="space-y-4">{rfqs.map((rfq) => <article key={rfq.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words text-lg font-bold text-slate-950">{rfq.title}</h3><p className="mt-1 text-sm text-slate-600">{rfq.quantity} {rfq.unit || "units"} · {formatMoney(rfq.budget)}{formatDate(rfq.createdAt) ? ` · ${formatDate(rfq.createdAt)}` : ""}</p></div><StatusBadge status={rfq.status}/></div>{rfq.description && <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600">{rfq.description}</p>}</div>
    <div className="border-t border-slate-200 bg-slate-50 p-5 sm:p-6"><h4 className="text-sm font-bold text-slate-950">Quotations ({rfq.quotes?.length || 0})</h4>{!rfq.quotes?.length ? <p className="mt-3 text-sm text-slate-600">Suppliers have not submitted quotations yet.</p> : <div className="mt-4 grid gap-3 lg:grid-cols-2">{rfq.quotes.map((quote) => <div key={quote.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-slate-950">{supplierName(quote.vendor)}</p><p className="mt-1 text-xl font-bold text-orange-700">{formatMoney(quote.price)}</p></div><StatusBadge status={quote.status}/></div><dl className="mt-3 space-y-1 text-sm text-slate-600">{quote.deliveryDays && <div><dt className="inline font-semibold">Delivery:</dt> <dd className="inline">{quote.deliveryDays} days</dd></div>}{formatDate(quote.createdAt) && <div><dt className="inline font-semibold">Received:</dt> <dd className="inline">{formatDate(quote.createdAt)}</dd></div>}</dl>{quote.message && <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{quote.message}</p>}{quote.status === "SENT" && rfq.status !== "CLOSED" && <div className="mt-4 flex gap-2"><button disabled={decisionId === quote.id} onClick={() => onDecision(quote.id, "ACCEPTED")} className="min-h-10 rounded-lg bg-emerald-700 px-4 text-xs font-bold text-white hover:bg-emerald-800 disabled:opacity-60">Accept</button><button disabled={decisionId === quote.id} onClick={() => onDecision(quote.id, "REJECTED")} className="min-h-10 rounded-lg border border-rose-200 px-4 text-xs font-bold text-rose-700 hover:bg-rose-50 disabled:opacity-60">Reject</button></div>}</div>)}</div>}</div>
  </article>)}</div>;
}
